### ISSUE TITLE
mupen64plus-next compatibility

### ISSUE THREAD

**Issue by marcrobledo** [Isotarge/dk64-tag-anywhere#2]
Is it really compatible with mupen64plus-next like the readme says? I have been testing it with RetroArch and it runs, but does not save game. (using patch V5). Haven't found any option to change the EEPROM type. Unpatched USA version saves fine.

Also, I'm curious... what's the reason of the battery type change in the patch? Does it store anything new else besides the settings (widescreen, fast mode, etc)? It would be cool if there was an alternate version that does not change battery type for everdrive/emulatores compatibility purposes (having to set widescreen and fast mode every time wouldn't be a critical loss).

Anyway... Thanks for this patch, I hope to make a 100% run as soon as possible, makes the game **much** more enjoyable :-)

**Comment by Isotarge** [comment]
The original game also uses an EEPROM 16k save type, this patch does not change that. Sorry to hear mupen64plus-next cannot detect it automatically.

Perhaps an issue or pull request should be opened on that upstream github repo to add this ROM Hack to their game-db to make it use EEPROM 16k automatically when the patched ROM is detected.

For now, you can use the savestate feature built into your libretro frontend to save your progress.

**Comment by Isotarge** [comment]
I have opened a pull request with mupen64plus-core to add the patched ROM to their mupen64plus.ini file, all going well we should see these changes show up in mupen64plus-next when they update their ini from upstream. I don't know how long that will take.

**Comment by marcrobledo** [comment]
Interesting.
I thought savegame type could be identified just by looking at the game's header like it's done in Game Boy.

Thanks for the answer!

**Comment by Isotarge** [comment]
Good news!
The mupen64plus-core PR has been merged, and mupen64plus-next has updated their core submodule which includes the fix.
Therefore, this should now be fixed the next time you update your libretro cores. If not, please re-open the issue.
Thanks for playing!
